name: Run-Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Run Ember Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Node Modules Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        run: yarn run test
