name: Run-Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        id: node-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Lint Addon
        working-directory: addon
        run: yarn run lint
      - name: Lint Test App
        working-directory: test-app
        run: yarn run lint
      - name: Lint Docs App
        working-directory: docs-app
        run: yarn run lint

  test-docs:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - name: Run Tests
        working-directory: docs-app
        run: yarn run test

  test:
    name: Run Ember Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ember-version:
          [
            embroider-safe,
            embroider-optimized,
            ember-lts-3.28,
            ember-lts-4.4,
            ember-lts-4.8,
            ember-lts-4.12,
          ]

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}-${{ matrix.ember-version }}
          restore-keys: |
            ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn --frozen-lockfile
      - run: yarn workspace addon build
      - name: Run Tests
        working-directory: test-app
        run: ./node_modules/.bin/ember try:one ${{ matrix.ember-version }} --skip-cleanup
