name: Run-Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      VOLTA_FEATURE_PNPM: 1

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Lint Addon
        working-directory: addon
        run: pnpm run lint
      - name: Lint Test App
        working-directory: test-app
        run: pnpm run lint
      - name: Lint Docs App
        working-directory: docs-app
        run: pnpm run lint

  test-docs:
    name: Test Docs
    runs-on: ubuntu-latest
    env:
      VOLTA_FEATURE_PNPM: 1
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: pnpm install
      - working-directory: addon
        run: pnpm run build
      - name: Run Tests
        working-directory: docs-app
        run: pnpm run test

  test:
    name: Run Ember Tests
    runs-on: ubuntu-latest
    env:
      VOLTA_FEATURE_PNPM: 1
    strategy:
      fail-fast: false
      matrix:
        ember-version:
          [
            embroider-safe,
            embroider-optimized,
            ember-lts-3.28,
            ember-lts-4.4,
            ember-lts-4.8,
            ember-lts-4.12,
          ]

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: pnpm install
      - working-directory: addon
        run: pnpm run build
      - name: Run Tests
        working-directory: test-app
        run: ./node_modules/.bin/ember try:one ${{ matrix.ember-version }} --skip-cleanup
