name: Run-Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Ember Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        id: node-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: yarn run lint

  test:
    name: Run Ember Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ember-version: [
          ember-lts-3.28,
          ember-lts-4.4,
          ember-lts-4.8,
          ember-lts-4.12
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}-${{ matrix.ember-version }}
          restore-keys: |
            ${{ runner.os }}-ci-yarn-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.ember-version }} --skip-cleanup
